"""Initial schema

Revision ID: e1175b51fe17
Revises: None
Create Date: 2026-07-21 16:37:31.003675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1175b51fe17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(length=512), nullable=True),
    sa.Column('backdrop_path', sa.String(length=512), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_tmdb_id'), 'collections', ['tmdb_id'], unique=True)
    op.create_table('downloads',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('download_speed_bps', sa.BigInteger(), nullable=False),
    sa.Column('eta_seconds', sa.Integer(), nullable=True),
    sa.Column('temp_path', sa.String(length=2048), nullable=True),
    sa.Column('dest_path', sa.String(length=2048), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=256), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downloads_external_id'), 'downloads', ['external_id'], unique=False)
    op.create_index(op.f('ix_downloads_status'), 'downloads', ['status'], unique=False)
    op.create_table('duplicates',
    sa.Column('media_id', sa.String(length=36), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('primary_file_path', sa.String(length=2048), nullable=False),
    sa.Column('duplicate_file_path', sa.String(length=2048), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('primary_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('duplicate_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('primary_resolution', sa.String(length=50), nullable=True),
    sa.Column('duplicate_resolution', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('duplicate_file_path')
    )
    op.create_index(op.f('ix_duplicates_media_id'), 'duplicates', ['media_id'], unique=False)
    op.create_table('genres',
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_tmdb_id'), 'genres', ['tmdb_id'], unique=True)
    op.create_table('health_reports',
    sa.Column('scan_type', sa.String(length=100), nullable=False),
    sa.Column('issues_found', sa.Integer(), nullable=False),
    sa.Column('issues_resolved', sa.Integer(), nullable=False),
    sa.Column('execution_time_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iptv_channels',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stream_url', sa.String(length=2048), nullable=False),
    sa.Column('logo_url', sa.String(length=2048), nullable=True),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('epg_id', sa.String(length=100), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iptv_channels_group_name'), 'iptv_channels', ['group_name'], unique=False)
    op.create_index(op.f('ix_iptv_channels_is_active'), 'iptv_channels', ['is_active'], unique=False)
    op.create_index(op.f('ix_iptv_channels_is_favorite'), 'iptv_channels', ['is_favorite'], unique=False)
    op.create_index(op.f('ix_iptv_channels_name'), 'iptv_channels', ['name'], unique=False)
    op.create_table('people',
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('profile_path', sa.String(length=512), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_imdb_id'), 'people', ['imdb_id'], unique=False)
    op.create_index(op.f('ix_people_name'), 'people', ['name'], unique=False)
    op.create_index(op.f('ix_people_tmdb_id'), 'people', ['tmdb_id'], unique=True)
    op.create_table('platform_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('source_service', sa.String(length=100), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_events_correlation_id'), 'platform_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_platform_events_event_type'), 'platform_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_platform_events_published_at'), 'platform_events', ['published_at'], unique=False)
    op.create_table('quality_rules',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('resolution_preference', sa.String(length=255), nullable=False),
    sa.Column('preferred_codecs', sa.String(length=255), nullable=False),
    sa.Column('require_hdr', sa.Boolean(), nullable=False),
    sa.Column('max_file_size_gb', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('radio_stations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stream_url', sa.String(length=2048), nullable=False),
    sa.Column('logo_url', sa.String(length=2048), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_radio_stations_country'), 'radio_stations', ['country'], unique=False)
    op.create_index(op.f('ix_radio_stations_genre'), 'radio_stations', ['genre'], unique=False)
    op.create_index(op.f('ix_radio_stations_is_active'), 'radio_stations', ['is_active'], unique=False)
    op.create_index(op.f('ix_radio_stations_is_favorite'), 'radio_stations', ['is_favorite'], unique=False)
    op.create_index(op.f('ix_radio_stations_name'), 'radio_stations', ['name'], unique=False)
    op.create_table('recordings',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=2048), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordings_file_path'), 'recordings', ['file_path'], unique=False)
    op.create_table('storage_reports',
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('free_bytes', sa.BigInteger(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studios',
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logo_path', sa.String(length=512), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studios_tmdb_id'), 'studios', ['tmdb_id'], unique=True)
    op.create_table('tv_shows',
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('first_air_date', sa.Date(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rating_tmdb', sa.Float(), nullable=True),
    sa.Column('rating_imdb', sa.Float(), nullable=True),
    sa.Column('poster_path', sa.String(length=1024), nullable=True),
    sa.Column('backdrop_path', sa.String(length=1024), nullable=True),
    sa.Column('poster_url', sa.String(length=1024), nullable=True),
    sa.Column('backdrop_url', sa.String(length=1024), nullable=True),
    sa.Column('folder_path', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tv_shows_imdb_id'), 'tv_shows', ['imdb_id'], unique=False)
    op.create_index(op.f('ix_tv_shows_title'), 'tv_shows', ['title'], unique=False)
    op.create_index(op.f('ix_tv_shows_tmdb_id'), 'tv_shows', ['tmdb_id'], unique=True)
    op.create_table('workflow_jobs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_jobs_correlation_id'), 'workflow_jobs', ['correlation_id'], unique=True)
    op.create_index(op.f('ix_workflow_jobs_media_id'), 'workflow_jobs', ['media_id'], unique=False)
    op.create_index(op.f('ix_workflow_jobs_status'), 'workflow_jobs', ['status'], unique=False)
    op.create_table('health_issues',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=2048), nullable=True),
    sa.Column('media_id', sa.String(length=36), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_details', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['health_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_issues_category'), 'health_issues', ['category'], unique=False)
    op.create_index(op.f('ix_health_issues_file_path'), 'health_issues', ['file_path'], unique=False)
    op.create_index(op.f('ix_health_issues_is_resolved'), 'health_issues', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_health_issues_media_id'), 'health_issues', ['media_id'], unique=False)
    op.create_index(op.f('ix_health_issues_report_id'), 'health_issues', ['report_id'], unique=False)
    op.create_table('movies',
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rating_tmdb', sa.Float(), nullable=True),
    sa.Column('rating_imdb', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('poster_path', sa.String(length=1024), nullable=True),
    sa.Column('backdrop_path', sa.String(length=1024), nullable=True),
    sa.Column('poster_url', sa.String(length=1024), nullable=True),
    sa.Column('backdrop_url', sa.String(length=1024), nullable=True),
    sa.Column('file_path', sa.String(length=2048), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('folder_path', sa.String(length=2048), nullable=True),
    sa.Column('collection_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_file_path'), 'movies', ['file_path'], unique=False)
    op.create_index(op.f('ix_movies_imdb_id'), 'movies', ['imdb_id'], unique=False)
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    op.create_index(op.f('ix_movies_tmdb_id'), 'movies', ['tmdb_id'], unique=True)
    op.create_index(op.f('ix_movies_year'), 'movies', ['year'], unique=False)
    op.create_table('seasons',
    sa.Column('tv_show_id', sa.String(length=36), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('poster_path', sa.String(length=1024), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tv_show_id'], ['tv_shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tv_show_id', 'season_number')
    )
    op.create_index(op.f('ix_seasons_tmdb_id'), 'seasons', ['tmdb_id'], unique=True)
    op.create_index(op.f('ix_seasons_tv_show_id'), 'seasons', ['tv_show_id'], unique=False)
    op.create_table('tv_show_genres',
    sa.Column('tv_show_id', sa.String(length=36), nullable=False),
    sa.Column('genre_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tv_show_id'], ['tv_shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tv_show_id', 'genre_id'),
    sa.UniqueConstraint('tv_show_id', 'genre_id')
    )
    op.create_table('workflow_steps',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['workflow_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_steps_job_id'), 'workflow_steps', ['job_id'], unique=False)
    op.create_index(op.f('ix_workflow_steps_status'), 'workflow_steps', ['status'], unique=False)
    op.create_table('episodes',
    sa.Column('tv_show_id', sa.String(length=36), nullable=False),
    sa.Column('season_id', sa.String(length=36), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('rating_tmdb', sa.Float(), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=2048), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tv_show_id'], ['tv_shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'episode_number')
    )
    op.create_index(op.f('ix_episodes_file_path'), 'episodes', ['file_path'], unique=False)
    op.create_index(op.f('ix_episodes_season_id'), 'episodes', ['season_id'], unique=False)
    op.create_index(op.f('ix_episodes_tmdb_id'), 'episodes', ['tmdb_id'], unique=True)
    op.create_index(op.f('ix_episodes_tv_show_id'), 'episodes', ['tv_show_id'], unique=False)
    op.create_table('movie_genres',
    sa.Column('movie_id', sa.String(length=36), nullable=False),
    sa.Column('genre_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id'),
    sa.UniqueConstraint('movie_id', 'genre_id')
    )
    op.create_table('movie_people',
    sa.Column('movie_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('character_name', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'person_id', 'role')
    )
    op.create_table('movie_studios',
    sa.Column('movie_id', sa.String(length=36), nullable=False),
    sa.Column('studio_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'studio_id'),
    sa.UniqueConstraint('movie_id', 'studio_id')
    )
    op.create_table('media_qualities',
    sa.Column('movie_id', sa.String(length=36), nullable=True),
    sa.Column('episode_id', sa.String(length=36), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=False),
    sa.Column('video_codec', sa.String(length=50), nullable=False),
    sa.Column('bitrate_kbps', sa.Integer(), nullable=True),
    sa.Column('is_hdr', sa.Boolean(), nullable=False),
    sa.Column('hdr_format', sa.String(length=50), nullable=True),
    sa.Column('frame_rate', sa.String(length=20), nullable=True),
    sa.Column('audio_codec', sa.String(length=50), nullable=False),
    sa.Column('audio_channels', sa.String(length=20), nullable=True),
    sa.Column('audio_language', sa.String(length=50), nullable=True),
    sa.Column('container', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_qualities_episode_id'), 'media_qualities', ['episode_id'], unique=False)
    op.create_index(op.f('ix_media_qualities_movie_id'), 'media_qualities', ['movie_id'], unique=False)
    op.create_table('subtitles',
    sa.Column('movie_id', sa.String(length=36), nullable=True),
    sa.Column('episode_id', sa.String(length=36), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('file_path', sa.String(length=2048), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('is_forced', sa.Boolean(), nullable=False),
    sa.Column('is_hearing_impaired', sa.Boolean(), nullable=False),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtitles_episode_id'), 'subtitles', ['episode_id'], unique=False)
    op.create_index(op.f('ix_subtitles_file_path'), 'subtitles', ['file_path'], unique=False)
    op.create_index(op.f('ix_subtitles_language'), 'subtitles', ['language'], unique=False)
    op.create_index(op.f('ix_subtitles_movie_id'), 'subtitles', ['movie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subtitles_movie_id'), table_name='subtitles')
    op.drop_index(op.f('ix_subtitles_language'), table_name='subtitles')
    op.drop_index(op.f('ix_subtitles_file_path'), table_name='subtitles')
    op.drop_index(op.f('ix_subtitles_episode_id'), table_name='subtitles')
    op.drop_table('subtitles')
    op.drop_index(op.f('ix_media_qualities_movie_id'), table_name='media_qualities')
    op.drop_index(op.f('ix_media_qualities_episode_id'), table_name='media_qualities')
    op.drop_table('media_qualities')
    op.drop_table('movie_studios')
    op.drop_table('movie_people')
    op.drop_table('movie_genres')
    op.drop_index(op.f('ix_episodes_tv_show_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_tmdb_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_season_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_file_path'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_workflow_steps_status'), table_name='workflow_steps')
    op.drop_index(op.f('ix_workflow_steps_job_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_table('tv_show_genres')
    op.drop_index(op.f('ix_seasons_tv_show_id'), table_name='seasons')
    op.drop_index(op.f('ix_seasons_tmdb_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_movies_year'), table_name='movies')
    op.drop_index(op.f('ix_movies_tmdb_id'), table_name='movies')
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.drop_index(op.f('ix_movies_imdb_id'), table_name='movies')
    op.drop_index(op.f('ix_movies_file_path'), table_name='movies')
    op.drop_table('movies')
    op.drop_index(op.f('ix_health_issues_report_id'), table_name='health_issues')
    op.drop_index(op.f('ix_health_issues_media_id'), table_name='health_issues')
    op.drop_index(op.f('ix_health_issues_is_resolved'), table_name='health_issues')
    op.drop_index(op.f('ix_health_issues_file_path'), table_name='health_issues')
    op.drop_index(op.f('ix_health_issues_category'), table_name='health_issues')
    op.drop_table('health_issues')
    op.drop_index(op.f('ix_workflow_jobs_status'), table_name='workflow_jobs')
    op.drop_index(op.f('ix_workflow_jobs_media_id'), table_name='workflow_jobs')
    op.drop_index(op.f('ix_workflow_jobs_correlation_id'), table_name='workflow_jobs')
    op.drop_table('workflow_jobs')
    op.drop_index(op.f('ix_tv_shows_tmdb_id'), table_name='tv_shows')
    op.drop_index(op.f('ix_tv_shows_title'), table_name='tv_shows')
    op.drop_index(op.f('ix_tv_shows_imdb_id'), table_name='tv_shows')
    op.drop_table('tv_shows')
    op.drop_index(op.f('ix_studios_tmdb_id'), table_name='studios')
    op.drop_table('studios')
    op.drop_table('storage_reports')
    op.drop_index(op.f('ix_recordings_file_path'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_radio_stations_name'), table_name='radio_stations')
    op.drop_index(op.f('ix_radio_stations_is_favorite'), table_name='radio_stations')
    op.drop_index(op.f('ix_radio_stations_is_active'), table_name='radio_stations')
    op.drop_index(op.f('ix_radio_stations_genre'), table_name='radio_stations')
    op.drop_index(op.f('ix_radio_stations_country'), table_name='radio_stations')
    op.drop_table('radio_stations')
    op.drop_table('quality_rules')
    op.drop_index(op.f('ix_platform_events_published_at'), table_name='platform_events')
    op.drop_index(op.f('ix_platform_events_event_type'), table_name='platform_events')
    op.drop_index(op.f('ix_platform_events_correlation_id'), table_name='platform_events')
    op.drop_table('platform_events')
    op.drop_index(op.f('ix_people_tmdb_id'), table_name='people')
    op.drop_index(op.f('ix_people_name'), table_name='people')
    op.drop_index(op.f('ix_people_imdb_id'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_iptv_channels_name'), table_name='iptv_channels')
    op.drop_index(op.f('ix_iptv_channels_is_favorite'), table_name='iptv_channels')
    op.drop_index(op.f('ix_iptv_channels_is_active'), table_name='iptv_channels')
    op.drop_index(op.f('ix_iptv_channels_group_name'), table_name='iptv_channels')
    op.drop_table('iptv_channels')
    op.drop_table('health_reports')
    op.drop_index(op.f('ix_genres_tmdb_id'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_duplicates_media_id'), table_name='duplicates')
    op.drop_table('duplicates')
    op.drop_index(op.f('ix_downloads_status'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_external_id'), table_name='downloads')
    op.drop_table('downloads')
    op.drop_index(op.f('ix_collections_tmdb_id'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
