version: "3.8"
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    networks:
      - media_network
    ports:
      - 8096:8096   # optional, for direct access
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /opt/media-platform/data/library/:/media
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata

networks:
  media_network:
    external: true

